# 과제1. car seat 매출 분석

* 카시트에 대해서 지역 매장 별 매출액을 살펴보고자 합니다.
* 행은 자사 매장이 있는 각 지역별 데이터 입니다.

![](https://cdn.images.express.co.uk/img/dynamic/24/590x/child-car-seat-986556.jpg?r=1532946857754)

## 0.환경설정

* 필요한 라이브러리 로딩, 데이터셋 가져오기

### 1) 라이브러리 로딩

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

### 2) 데이터 불러오기

In [3]:
path = 'https://raw.githubusercontent.com/JunhoYu/Data-Analysis/main/Carseats.csv'
data = pd.read_csv(path)
data.head(10)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
5,10.81,124,113,13,501,72,Bad,78,16,No,Yes
6,6.63,115,105,0,45,108,Medium,71,15,Yes,No
7,11.85,136,81,15,425,120,Good,67,10,Yes,Yes
8,6.54,132,110,0,108,124,Medium,76,10,No,No
9,4.69,132,113,0,131,124,Medium,76,17,No,Yes

|	변수명	|	설명	|	구분	|
|	----	|	----	|	----	|
|	Sales 	|	 각 지역 판매량(단위 : 1000개)	|	Target	|
|	CompPrice 	|	 각 지역 경쟁사 가격(단위 : 달러)	|	feature	|
|	Income 	|	 각 지역 소득수준(단위 : 천달러)	|	feature	|
|	Advertising 	|	 각 지역, 회사의 광고 예산(단위 : 1000달러)	|	feature	|
|	Population 	|	 지역 인구수(단위 : 1000명)	|	feature	|
|	Price 	|	 자사 지역별 판매가격(달러)	|	feature	|
|	Education 	|	 교육수준(10~18), 범주	|	feature	|
|	ShelveLoc 	|	 진열상태(Good, Medium, Bad)	|	feature	|
|	Age 	|	 지역 인구의 평균 연령	|	feature	|
|	US 	|	 매장이 미국에 있는지 여부(Yes, No)	|	feature	|
|	Urban 	|	 매장이 도심에 있는지 여부(Yes, No)	|	feature	|

## 1.데이터 살펴보기

* 주어진 데이터로부터 다양한 조회 방법을 통해 비즈니스 사항을 파악해 봅시다.
* 데이터와 비즈니스를 파악하기 위한 질문을 10개 이상 도출하고, 조회해 봅시다.

In [4]:
data.tail(10)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
390,5.47,108,75,9,61,111,Medium,67,12,Yes,Yes
391,6.10,153,63,0,49,124,Bad,56,16,Yes,No
392,4.53,129,42,13,315,130,Bad,34,13,Yes,Yes
393,5.57,109,51,10,26,120,Medium,30,17,No,Yes
394,5.35,130,58,19,366,139,Bad,33,16,Yes,Yes
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [8]:
print("행렬 갯수")
print(data.shape)

행렬 갯수
(400, 11)

In [26]:
print(data.columns)
print(data.columns[1])
print("열확인")
print("-"*50)
print(data.columns.values)
print(data.columns.values[0])
print(data.columns.values[1])
if data.columns.values[0]==data.columns[0]:
    print("values 안써도 된다 형태만 array 그냥 리스트 형인가 어레이 형인가의 차이")
print("열 확인 data.columns.values")

Index(['Sales', 'CompPrice', 'Income', 'Advertising', 'Population', 'Price',
       'ShelveLoc', 'Age', 'Education', 'Urban', 'US'],
      dtype='object')
CompPrice
열확인
--------------------------------------------------
['Sales' 'CompPrice' 'Income' 'Advertising' 'Population' 'Price'
 'ShelveLoc' 'Age' 'Education' 'Urban' 'US']
Sales
CompPrice
values 안써도 된다 형태만 array

In [28]:
print(list(data))
print("리스트 형태")
print("열 이름을 리스트 형태로 아까꺼랑은 다름 ")
print("list(data)는 열이름을 리스트로 반환")

['Sales', 'CompPrice', 'Income', 'Advertising', 'Population', 'Price', 'ShelveLoc', 'Age', 'Education', 'Urban', 'US']
리스트 형태
열 이름을 리스트 형태로 아까꺼랑은 다름

In [30]:
'''
int64: 정수형 데이터(int)
float64: 실수형 데이터(float)
object: 문자열 데이터(string)
'''
print(data.dtypes)

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [36]:
# 열 자료형, 값 개수 확인
print(data.info())
#1196행 11열 전부 보여줌

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    object
 7   Age          400 non-null    int64
 8   Education    400 non-null    int64
 9   Urban        400 non-null    object
 10  US           400 non-null    object
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB
None

In [40]:
print(data.describe())

            Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000
mean     7.496325  124.975000   68.657500     6.635000  264.840000
std      2.824115   15.334512   27.986037     6.650364  147.376436
min      0.000000   77.000000   21.000000     0.000000   10.000000
25%      5.390000  115.000000   42.750000     0.000000  139.000000
50%      7.490000  125.000000   69.000000     5.000000  272.000000
75%      9.320000  135.000000   91.000000    12.000000  398.500000
max     16.270000  175.000000  120.000000    29.000000  509.000000

            Price         Age   Education
count  400.000000  400.000000  400.000000
mean   115.795000   53.322500   13.900000
std     23.676664   16.200297    2.620528
min     24.000000   25.000000   10.000000
25%    100.000000   39.750000   12.000000
50%    117.000000   54.500000   14.000000
75%    131.000000   66.000000   16.000000
max    191.000000   80.000000   18.000000

In [42]:
print(data[['Sales','CompPrice']].describe())

            Sales   CompPrice
count  400.000000  400.000000
mean     7.496325  124.975000
std      2.824115   15.334512
min      0.000000   77.000000
25%      5.390000  115.000000
50%      7.490000  125.000000
75%      9.320000  135.000000
max     16.270000  175.000000

In [44]:
print(data['Sales'].describe())

count    400.000000
mean       7.496325
std        2.824115
min        0.000000
25%        5.390000
50%        7.490000
75%        9.320000
max       16.270000
Name: Sales, dtype: float64

In [52]:
print(data.sort_values(by='Age',ascending=False))

     Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
257   8.67        125      62           14         477    112    Medium   80
91    4.81         97      46           11         267    107    Medium   80
137   6.52        128      42            0         436    118    Medium   80
255   7.71        123      81            8         198     81       Bad   80
221   6.43        124      44            0         125    107    Medium   80
..     ...        ...     ...          ...         ...    ...       ...  ...
218   9.70        138      61           12         156    120    Medium   25
182   4.74        137      60            4         230    140       Bad   25
175   7.54        115      89            0          38    122    Medium   25
178  10.66        104      71           14          89     81    Medium   25
153   5.93        150      36            7         488    150    Medium   25

     Education Urban   US
257         13   Yes  Yes
91          15   Yes  Yes
137         11   Yes   No
255         15   Yes  Yes
221         11   Yes   No
..         ...   ...  ...
218         14   Yes  Yes
182         13   Yes   No
175         12   Yes   No
178         14    No  Yes
153         17    No  Yes

[400 rows x 11 columns]

In [51]:
print(data.sort_values(by='Age',ascending=True))

     Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
363  10.26        111      75            1         377    108      Good   25
263   7.77        116      26            6         434    115    Medium   25
203   2.05        131      82            0         132    157       Bad   25
178  10.66        104      71           14          89     81    Medium   25
218   9.70        138      61           12         156    120    Medium   25
..     ...        ...     ...          ...         ...    ...       ...  ...
116   5.08        135      75            0         202    128    Medium   80
183   5.32        118      74            6         426    102    Medium   80
137   6.52        128      42            0         436    118    Medium   80
50    1.42         99      32           18         341    108       Bad   80
257   8.67        125      62           14         477    112    Medium   80

     Education Urban   US
363         12   Yes   No
263         17   Yes  Yes
203         14   Yes   No
178         14    No  Yes
218         14   Yes  Yes
..         ...   ...  ...
116         10    No   No
183         18   Yes  Yes
137         11   Yes   No
50          16   Yes  Yes
257         13   Yes  Yes

[400 rows x 11 columns]

In [67]:
data.sort_values(by=['Price','Advertising','Age','Education'],ascending=[True,True,True,True]).head(50)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
42,10.43,77,69,0,25,24,Medium,50,18,Yes,No
125,9.34,89,78,0,181,49,Medium,43,15,No,No
367,14.37,95,106,0,256,53,Good,52,17,Yes,No
313,9.33,103,81,3,491,54,Medium,66,13,Yes,No
171,12.49,93,106,12,416,55,Medium,75,15,Yes,Yes
272,12.98,113,33,0,14,63,Good,38,12,Yes,No
208,7.78,86,54,0,497,64,Bad,33,12,Yes,No
18,13.91,110,110,0,408,68,Good,46,17,No,Yes
383,9.35,98,117,0,76,68,Medium,63,10,Yes,No
155,7.71,98,72,0,59,69,Medium,65,16,Yes,No
159,9.32,119,60,0,372,70,Bad,30,18,No,No
76,10.64,102,87,10,346,70,Medium,64,15,Yes,Yes
46,12.44,127,90,14,16,70,Medium,48,15,No,Yes
229,11.19,98,104,0,404,72,Medium,27,18,No,No
357,13.36,103,73,3,276,72,Medium,34,15,Yes,Yes
287,6.88,95,44,4,208,72,Bad,44,17,Yes,Yes
316,15.63,122,36,5,369,72,Good,35,10,Yes,Yes
5,10.81,124,113,13,501,72,Bad,78,16,No,Yes
292,11.82,113,66,16,322,74,Good,76,15,Yes,Yes
130,8.41,94,84,13,497,77,Medium,51,12,Yes,Yes
169,11.48,104,41,15,492,77,Good,73,18,Yes,Yes
388,8.14,135,89,11,245,78,Bad,79,16,Yes,Yes
368,10.71,109,22,10,348,79,Good,74,14,No,Yes
80,8.01,113,100,16,353,79,Bad,68,11,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
309,11.18,131,111,13,33,80,Bad,68,18,Yes,Yes
258,3.47,108,38,0,251,81,Bad,72,14,No,No
255,7.71,123,81,8,198,81,Bad,80,15,Yes,Yes
178,10.66,104,71,14,89,81,Medium,25,14,No,Yes
225,6.68,107,25,0,412,82,Bad,36,14,Yes,No
25,14.90,139,32,0,176,82,Good,54,11,No,No
334,7.63,93,117,9,489,83,Bad,42,13,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
56,11.91,133,82,0,54,84,Medium,50,17,Yes,No
94,8.39,115,97,5,134,84,Bad,55,11,Yes,Yes
186,8.68,120,51,0,93,86,Medium,46,17,No,No
273,10.04,116,106,8,244,86,Medium,58,12,Yes,Yes
13,10.96,115,28,11,29,86,Good,53,18,Yes,Yes
301,7.41,99,93,0,198,87,Medium,57,16,Yes,Yes
121,11.67,125,89,10,380,87,Bad,28,10,Yes,Yes
149,11.48,121,120,13,140,87,Medium,56,11,Yes,Yes
245,10.00,114,43,0,199,88,Good,57,10,No,Yes
270,11.99,119,26,0,284,89,Good,26,10,Yes,No
30,13.55,125,94,0,447,89,Good,30,12,Yes,No
291,6.64,118,70,0,106,89,Bad,39,17,Yes,No
293,11.28,123,84,0,74,89,Good,59,10,Yes,No
329,11.27,100,54,9,433,89,Good,45,12,Yes,Yes
380,9.64,106,64,10,17,89,Medium,68,17,Yes,Yes
77,7.70,118,71,12,44,89,Medium,67,18,No,Yes
79,9.14,134,67,0,286,90,Bad,41,13,Yes,No

In [68]:
data.sort_values(by=['Advertising','Price','Age','Education'],ascending=[True,True,True,True]).head(50)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
42,10.43,77,69,0,25,24,Medium,50,18,Yes,No
125,9.34,89,78,0,181,49,Medium,43,15,No,No
367,14.37,95,106,0,256,53,Good,52,17,Yes,No
272,12.98,113,33,0,14,63,Good,38,12,Yes,No
208,7.78,86,54,0,497,64,Bad,33,12,Yes,No
18,13.91,110,110,0,408,68,Good,46,17,No,Yes
383,9.35,98,117,0,76,68,Medium,63,10,Yes,No
155,7.71,98,72,0,59,69,Medium,65,16,Yes,No
159,9.32,119,60,0,372,70,Bad,30,18,No,No
229,11.19,98,104,0,404,72,Medium,27,18,No,No
258,3.47,108,38,0,251,81,Bad,72,14,No,No
225,6.68,107,25,0,412,82,Bad,36,14,Yes,No
25,14.90,139,32,0,176,82,Good,54,11,No,No
56,11.91,133,82,0,54,84,Medium,50,17,Yes,No
186,8.68,120,51,0,93,86,Medium,46,17,No,No
301,7.41,99,93,0,198,87,Medium,57,16,Yes,Yes
245,10.00,114,43,0,199,88,Good,57,10,No,Yes
270,11.99,119,26,0,284,89,Good,26,10,Yes,No
30,13.55,125,94,0,447,89,Good,30,12,Yes,No
291,6.64,118,70,0,106,89,Bad,39,17,Yes,No
293,11.28,123,84,0,74,89,Good,59,10,Yes,No
79,9.14,134,67,0,286,90,Bad,41,13,Yes,No
109,8.98,115,65,0,217,90,Medium,60,17,No,No
188,8.07,116,37,0,426,90,Medium,76,15,Yes,No
340,7.50,140,29,0,105,91,Bad,43,16,Yes,No
66,8.85,127,92,0,508,91,Medium,56,18,Yes,No
181,7.43,121,83,0,79,91,Medium,68,11,Yes,No
192,7.56,108,26,0,408,93,Medium,56,14,No,No
167,6.71,106,73,0,216,93,Medium,60,13,Yes,No
341,7.38,98,120,0,268,93,Medium,72,10,No,No
177,10.48,138,72,0,148,94,Medium,27,17,Yes,Yes
241,12.01,136,63,0,160,94,Medium,38,12,Yes,No
187,6.03,117,32,0,142,96,Bad,62,17,Yes,No
103,5.07,123,91,0,334,96,Bad,78,17,Yes,Yes
28,2.99,103,74,0,359,97,Bad,55,11,Yes,Yes
207,8.19,111,105,0,466,97,Bad,61,10,No,No
102,5.30,113,22,0,57,97,Medium,65,16,No,No
148,7.56,110,119,0,384,97,Medium,72,14,No,Yes
288,6.98,116,40,0,74,97,Medium,76,15,No,No
372,7.80,121,50,0,508,98,Medium,65,11,No,No
48,3.91,116,52,0,349,98,Bad,69,18,Yes,No
69,7.99,127,59,0,339,99,Medium,65,12,Yes,No
244,8.78,130,30,0,391,100,Medium,26,18,Yes,No
36,8.89,122,76,0,270,100,Good,60,18,No,No
338,5.97,112,24,0,164,101,Medium,45,11,Yes,No
248,5.36,111,52,0,12,101,Medium,61,11,Yes,Yes
38,6.59,109,73,0,454,102,Medium,65,15,Yes,No
337,8.61,130,38,0,283,102,Medium,80,15,Yes,No
90,5.33,115,22,0,491,103,Medium,64,11,No,No
93,8.86,145,30,0,67,104,Medium,55,17,Yes,No

In [70]:
data.sort_values(by=['Education','Price','Advertising','Age'],ascending=[True,True,True,True]).head(50)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
383,9.35,98,117,0,76,68,Medium,63,10,Yes,No
316,15.63,122,36,5,369,72,Good,35,10,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
121,11.67,125,89,10,380,87,Bad,28,10,Yes,Yes
245,10.00,114,43,0,199,88,Good,57,10,No,Yes
270,11.99,119,26,0,284,89,Good,26,10,Yes,No
293,11.28,123,84,0,74,89,Good,59,10,Yes,No
341,7.38,98,120,0,268,93,Medium,72,10,No,No
193,13.28,139,70,7,71,96,Good,61,10,Yes,Yes
207,8.19,111,105,0,466,97,Bad,61,10,No,No
10,9.01,121,78,9,150,100,Bad,26,10,No,Yes
260,7.67,129,117,8,400,101,Bad,36,10,Yes,Yes
297,3.07,118,83,13,276,104,Bad,75,10,Yes,Yes
185,10.07,130,100,11,449,107,Medium,64,10,Yes,Yes
122,6.88,119,100,5,45,108,Medium,75,10,Yes,Yes
236,9.32,141,34,16,361,108,Medium,69,10,Yes,Yes
23,5.87,121,31,0,292,109,Medium,79,10,Yes,No
138,10.27,125,103,12,371,109,Medium,44,10,Yes,Yes
37,4.95,121,41,5,412,110,Medium,54,10,Yes,Yes
243,7.82,124,25,13,87,110,Medium,57,10,Yes,Yes
88,6.56,117,42,7,144,111,Medium,62,10,Yes,Yes
158,12.53,142,90,1,189,112,Good,39,10,No,Yes
150,10.49,122,84,8,176,114,Good,57,10,No,Yes
168,7.30,129,89,0,425,117,Medium,45,10,Yes,No
170,8.01,128,39,12,356,118,Medium,71,10,Yes,Yes
342,7.81,137,102,13,422,118,Medium,71,10,No,Yes
7,11.85,136,81,15,425,120,Good,67,10,Yes,Yes
8,6.54,132,110,0,108,124,Medium,76,10,No,No
220,10.59,131,120,15,262,124,Medium,30,10,Yes,Yes
308,9.24,126,80,19,436,126,Medium,52,10,Yes,Yes
116,5.08,135,75,0,202,128,Medium,80,10,No,No
198,3.62,112,80,5,500,128,Medium,69,10,Yes,Yes
202,4.10,121,78,4,413,130,Bad,46,10,No,Yes
285,7.60,146,26,11,261,131,Medium,39,10,Yes,Yes
17,12.29,147,74,13,251,131,Good,52,10,Yes,Yes
304,11.93,123,98,12,408,134,Good,29,10,Yes,Yes
331,10.10,135,63,15,213,134,Medium,32,10,Yes,Yes
312,6.80,137,117,5,337,135,Bad,38,10,Yes,Yes
237,9.62,151,28,8,499,135,Medium,48,10,Yes,Yes
132,9.54,125,87,9,232,136,Good,72,10,Yes,Yes
32,6.20,107,32,12,236,137,Good,64,10,No,Yes
295,4.21,118,35,14,502,137,Medium,79,10,No,Yes
39,3.24,130,60,0,144,138,Bad,38,10,No,No
213,8.23,149,84,5,220,139,Medium,33,10,Yes,Yes
256,4.20,147,40,0,277,144,Medium,73,10,Yes,No
280,2.86,121,86,10,496,145,Bad,51,10,Yes,Yes
129,4.47,143,120,7,279,147,Bad,40,10,No,Yes
333,5.87,136,60,7,303,147,Medium,41,10,Yes,Yes
80,8.01,113,100,16,353,79,Bad,68,11,Yes,Yes
25,14.90,139,32,0,176,82,Good,54,11,No,No

In [73]:
data.sort_values(by=['Education','Price','Advertising','Age'],ascending=[True,True,True,True]).reset_index().head(50)
#복합 정렬 배치 교육 가격 광고 나이 순 저거 순서 바꾸면 바뀜

,index,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,383,9.35,98,117,0,76,68,Medium,63,10,Yes,No
1,316,15.63,122,36,5,369,72,Good,35,10,Yes,Yes
2,1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
3,121,11.67,125,89,10,380,87,Bad,28,10,Yes,Yes
4,245,10.00,114,43,0,199,88,Good,57,10,No,Yes
5,270,11.99,119,26,0,284,89,Good,26,10,Yes,No
6,293,11.28,123,84,0,74,89,Good,59,10,Yes,No
7,341,7.38,98,120,0,268,93,Medium,72,10,No,No
8,193,13.28,139,70,7,71,96,Good,61,10,Yes,Yes
9,207,8.19,111,105,0,466,97,Bad,61,10,No,No
10,10,9.01,121,78,9,150,100,Bad,26,10,No,Yes
11,260,7.67,129,117,8,400,101,Bad,36,10,Yes,Yes
12,297,3.07,118,83,13,276,104,Bad,75,10,Yes,Yes
13,185,10.07,130,100,11,449,107,Medium,64,10,Yes,Yes
14,122,6.88,119,100,5,45,108,Medium,75,10,Yes,Yes
15,236,9.32,141,34,16,361,108,Medium,69,10,Yes,Yes
16,23,5.87,121,31,0,292,109,Medium,79,10,Yes,No
17,138,10.27,125,103,12,371,109,Medium,44,10,Yes,Yes
18,37,4.95,121,41,5,412,110,Medium,54,10,Yes,Yes
19,243,7.82,124,25,13,87,110,Medium,57,10,Yes,Yes
20,88,6.56,117,42,7,144,111,Medium,62,10,Yes,Yes
21,158,12.53,142,90,1,189,112,Good,39,10,No,Yes
22,150,10.49,122,84,8,176,114,Good,57,10,No,Yes
23,168,7.30,129,89,0,425,117,Medium,45,10,Yes,No
24,170,8.01,128,39,12,356,118,Medium,71,10,Yes,Yes
25,342,7.81,137,102,13,422,118,Medium,71,10,No,Yes
26,7,11.85,136,81,15,425,120,Good,67,10,Yes,Yes
27,8,6.54,132,110,0,108,124,Medium,76,10,No,No
28,220,10.59,131,120,15,262,124,Medium,30,10,Yes,Yes
29,308,9.24,126,80,19,436,126,Medium,52,10,Yes,Yes
30,116,5.08,135,75,0,202,128,Medium,80,10,No,No
31,198,3.62,112,80,5,500,128,Medium,69,10,Yes,Yes
32,202,4.10,121,78,4,413,130,Bad,46,10,No,Yes
33,285,7.60,146,26,11,261,131,Medium,39,10,Yes,Yes
34,17,12.29,147,74,13,251,131,Good,52,10,Yes,Yes
35,304,11.93,123,98,12,408,134,Good,29,10,Yes,Yes
36,331,10.10,135,63,15,213,134,Medium,32,10,Yes,Yes
37,312,6.80,137,117,5,337,135,Bad,38,10,Yes,Yes
38,237,9.62,151,28,8,499,135,Medium,48,10,Yes,Yes
39,132,9.54,125,87,9,232,136,Good,72,10,Yes,Yes
40,32,6.20,107,32,12,236,137,Good,64,10,No,Yes
41,295,4.21,118,35,14,502,137,Medium,79,10,No,Yes
42,39,3.24,130,60,0,144,138,Bad,38,10,No,No
43,213,8.23,149,84,5,220,139,Medium,33,10,Yes,Yes
44,256,4.20,147,40,0,277,144,Medium,73,10,Yes,No
45,280,2.86,121,86,10,496,145,Bad,51,10,Yes,Yes
46,129,4.47,143,120,7,279,147,Bad,40,10,No,Yes
47,333,5.87,136,60,7,303,147,Medium,41,10,Yes,Yes
48,80,8.01,113,100,16,353,79,Bad,68,11,Yes,Yes
49,25,14.90,139,32,0,176,82,Good,54,11,No,No

In [75]:
data.sort_values(by=['Education','Price','Advertising','Age'],ascending=[True,True,True,True]).reset_index(drop=False).head(10)

,index,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,383,9.35,98,117,0,76,68,Medium,63,10,Yes,No
1,316,15.63,122,36,5,369,72,Good,35,10,Yes,Yes
2,1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
3,121,11.67,125,89,10,380,87,Bad,28,10,Yes,Yes
4,245,10.00,114,43,0,199,88,Good,57,10,No,Yes
5,270,11.99,119,26,0,284,89,Good,26,10,Yes,No
6,293,11.28,123,84,0,74,89,Good,59,10,Yes,No
7,341,7.38,98,120,0,268,93,Medium,72,10,No,No
8,193,13.28,139,70,7,71,96,Good,61,10,Yes,Yes
9,207,8.19,111,105,0,466,97,Bad,61,10,No,No

In [76]:
data.sort_values(by=['Education','Price','Advertising','Age'],ascending=[True,True,True,True]).reset_index(drop=True).head(10)
#이거 의미 없음

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.35,98,117,0,76,68,Medium,63,10,Yes,No
1,15.63,122,36,5,369,72,Good,35,10,Yes,Yes
2,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
3,11.67,125,89,10,380,87,Bad,28,10,Yes,Yes
4,10.00,114,43,0,199,88,Good,57,10,No,Yes
5,11.99,119,26,0,284,89,Good,26,10,Yes,No
6,11.28,123,84,0,74,89,Good,59,10,Yes,No
7,7.38,98,120,0,268,93,Medium,72,10,No,No
8,13.28,139,70,7,71,96,Good,61,10,Yes,Yes
9,8.19,111,105,0,466,97,Bad,61,10,No,No

In [82]:
print(data.head(5))

   Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42
1  11.22        111      48           16         260     83      Good   65
2  10.06        113      35           10         269     80    Medium   59
3   7.40        117     100            4         466     97    Medium   55
4   4.15        141      64            3         340    128       Bad   38

   Education Urban   US
0         17   Yes  Yes
1         10   Yes  Yes
2         12   Yes  Yes
3         14   Yes  Yes
4         13   Yes   No

In [78]:
print(data['Sales'])

0       9.50
1      11.22
2      10.06
3       7.40
4       4.15
       ...
395    12.57
396     6.14
397     7.41
398     5.94
399     9.71
Name: Sales, Length: 400, dtype: float64

In [83]:
print(type(data['Age']))
#시리즈다

<class 'pandas.core.series.Series'>

In [85]:
print(data['Age'].unique())

[42 65 59 55 38 78 71 67 76 26 50 62 53 52 63 46 69 35 79 54 64 58 30 44
 60 73 48 32 80 75 39 61 74 29 77 56 47 25 31 36 41 68 70 28 43 49 45 33
 34 51 40 72 57 27 66 37]

In [90]:
print(data['Urban'].unique())

['Yes' 'No']

In [87]:
print(data.columns)

Index(['Sales', 'CompPrice', 'Income', 'Advertising', 'Population', 'Price',
       'ShelveLoc', 'Age', 'Education', 'Urban', 'US'],
      dtype='object')

In [91]:
print(data['ShelveLoc'].unique())

['Bad' 'Good' 'Medium']

In [93]:
print(data['ShelveLoc'].value_counts())

Medium    219
Bad        96
Good       85
Name: ShelveLoc, dtype: int64

In [111]:
print(data[['ShelveLoc','Income']].value_counts())

ShelveLoc  Income
Medium     69        9
           73        5
           26        5
           84        5
           100       5
                    ..
Good       36        1
           38        1
Medium     23        1
Good       39        1
Bad        21        1
Length: 212, dtype: int64

In [94]:
print(data.head(10))

   Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42
1  11.22        111      48           16         260     83      Good   65
2  10.06        113      35           10         269     80    Medium   59
3   7.40        117     100            4         466     97    Medium   55
4   4.15        141      64            3         340    128       Bad   38
5  10.81        124     113           13         501     72       Bad   78
6   6.63        115     105            0          45    108    Medium   71
7  11.85        136      81           15         425    120      Good   67
8   6.54        132     110            0         108    124    Medium   76
9   4.69        132     113            0         131    124    Medium   76

   Education Urban   US
0         17   Yes  Yes
1         10   Yes  Yes
2         12   Yes  Yes
3         14   Yes  Yes
4         13   Yes   No
5         16    No  Yes
6         15   Yes   No
7         10   Yes  Yes
8         10    No   No
9         17    No  Yes

In [97]:
print(data['CompPrice'].sum())

49990

In [98]:
print(data['ShelveLoc'].sum())

BadGoodMediumMediumBadBadMediumGoodMediumMediumBadGoodMediumGoodGoodMediumGoodGoodGoodMediumMediumGoodMediumMediumBadGoodGoodMediumBadBadGoodMediumGoodGoodMediumMediumGoodMediumMediumBadBadBadMediumMediumMediumBadMediumBadBadGoodBadBadBadMediumMediumMediumMediumBadBadMediumBadMediumBadMediumMediumMediumMediumMediumGoodMediumGoodMediumMediumGoodMediumBadMediumMediumMediumBadBadGoodGoodBadBadMediumMediumGoodMediumMediumMediumMediumMediumMediumBadMediumGoodBadGoodBadMediumMediumMediumBadMediumMediumMediumMediumBadMediumMediumMediumGoodBadMediumMediumMediumMediumMediumMediumMediumBadMediumGoodGoodMediumGoodMediumBadBadMediumMediumGoodBadMediumMediumBadMediumMediumMediumMediumBadMediumBadGoodMediumBadGoodMediumMediumGoodGoodGoodMediumMediumMediumGoodMediumGoodBadMediumMediumMediumBadMediumBadMediumMediumMediumGoodMediumMediumGoodMediumMediumMediumMediumMediumMediumMediumBadMediumBadMediumMediumMediumMediumBadMediumMediumMediumGoodMediumGoodMediumBadBadMediumMediumMediumMediumMediumBadBadMediumMediumMediumBadBadBadBadMediumMediumMediumMediumBadMediumMediumMediumGoodMediumMediumMediumMediumMediumBadGoodMediumBadMediumBadMediumGoodMediumGoodMediumMediumMediumGoodBadMediumMediumMediumMediumMediumGoodBadBadMediumBadGoodBadMediumMediumGoodBadMediumMediumBadBadBadMediumMediumMediumGoodBadGoodBadMediumMediumGoodMediumGoodMediumMediumMediumMediumMediumGoodMediumBadGoodGoodMediumBadMediumMediumBadMediumMediumMediumBadGoodGoodGoodMediumGoodBadGoodMediumMediumMediumBadMediumGoodMediumMediumBadMediumBadMediumBadBadMediumGoodGoodGoodGoodGoodMediumMediumMediumGoodMediumBadMediumMediumMediumBadGoodBadMediumMediumMediumBadMediumBadMediumMediumGoodBadMediumMediumBadGoodGoodMediumGoodGoodMediumMediumMediumGoodMediumMediumGoodGoodMediumBadBadGoodMediumBadGoodGoodMediumMediumGoodGoodMediumBadMediumMediumMediumMediumMediumGoodMediumMediumBadMediumBadMediumMediumGoodMediumMediumMediumBadMediumMediumBadBadMediumBadGoodMediumMediumBadGood

In [99]:
print(data['CompPrice'].max())

175

In [100]:
print(data['CompPrice'].min())

77

In [101]:
print(data['ShelveLoc'].max())

Medium

In [102]:
print(data['ShelveLoc'].min())

Bad

In [103]:
print(data[['CompPrice','Age']].min())

CompPrice    77
Age          25
dtype: int64

In [104]:
print(data[['CompPrice','Age']].mean())

CompPrice    124.9750
Age           53.3225
dtype: float64

In [107]:
print(data[['CompPrice','Age']].median())

CompPrice    125.0
Age           54.5
dtype: float64